version: '3.3'
services:
  app:
    build: ./app
    ports:
    - "3000:3000"
    volumes:
    - ./app:/app:delegated
    - node_modules:/app/node_modules
    - packs:/app/public/packs
    - bundle:/usr/local/bundle
    depends_on:
      - pgsql
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
    command: "bundle exec rails server -b '0.0.0.0'"

  pgsql:
    image: postgres:12
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  node_modules:
  packs:
  bundle:
  postgres:



